### ISSUE TITLE
Changer les répertoire

### ISSUE THREAD

**Issue by surfeur5** [silarhi/docker-php#3]
Bonjour,

Je me base sur votre system pour créer ma propre image custom, mais je rencontre un souci.

J'ai créé un volume en modifient le DockerFils, mais les fichiers de mon conteneur ne vous pas dedans cela fait qu'elle que jour que je cherche, mais je ne trouve pas la solution pouvez m'aider. 

En vous remerciant par avance

**Comment by guillaume-sainthillier** [comment]
Bonjour,

Vous pouvez utiliser le système de volume docker pour mettre à jour le répertoire /app en temps réel, je vous invite à consulter la documentation de docker à ce sujet.

ce problème n’étant pas lié à l’image PHP, je clôture ce ticket.
